apiVersion : apps/v1
kind: Deployment
metadata:
  name: mnovikovpipeline 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnovikovpipeline
  template:
    metadata:
      labels:
        app: mnovikovpipeline 
    spec:
      containers:
        - name: mnovikovpipeline 
          image: aksdevopsmn.azurecr.io/mnovikovpipeline
          ports:
          - containerPort: 80